import { mkdtemp, readFile, readdir, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import type { EmitContext, SkillContent } from "../src/emitter/base.js";
import { assembleMarkdown, renderEager, renderLazy, renderSkill } from "../src/emitter/base.js";
import { ClaudeCodeEmitter } from "../src/emitter/claude-code.js";
import { CodexEmitter } from "../src/emitter/codex.js";
import { CursorEmitter, CursorLegacyEmitter } from "../src/emitter/cursor.js";
import { GenericEmitter } from "../src/emitter/generic.js";

const SAMPLE_SKILL: SkillContent = {
	id: "test/repo/sample",
	frontmatter: {
		name: "sample",
		description: "A sample skill for testing",
	},
	body: "# Sample\n\nDo the thing.",
};

const LAZY_SKILL: SkillContent = {
	...SAMPLE_SKILL,
	inject: "lazy" as const,
};

describe("renderEager", () => {
	it("includes full body content", () => {
		const result = renderEager(SAMPLE_SKILL);
		expect(result).toContain("## sample");
		expect(result).toContain("A sample skill for testing");
		expect(result).toContain("Do the thing.");
	});
});

describe("renderLazy", () => {
	it("includes only metadata", () => {
		const result = renderLazy(SAMPLE_SKILL);
		expect(result).toContain("## sample");
		expect(result).toContain("loaded on demand");
		expect(result).not.toContain("Do the thing.");
	});
});

describe("renderSkill", () => {
	it("respects per-skill inject override", () => {
		const result = renderSkill(LAZY_SKILL, "eager");
		expect(result).toContain("loaded on demand");
		expect(result).not.toContain("Do the thing.");
	});

	it("falls back to default strategy when no override", () => {
		const result = renderSkill(SAMPLE_SKILL, "lazy");
		expect(result).toContain("loaded on demand");
	});

	it("uses eager when strategy is eager and no override", () => {
		const result = renderSkill(SAMPLE_SKILL, "eager");
		expect(result).toContain("Do the thing.");
	});
});

describe("assembleMarkdown", () => {
	it("produces a valid markdown document", () => {
		const ctx: EmitContext = {
			projectDir: "/tmp/test",
			skills: [SAMPLE_SKILL],
			strategy: "eager",
		};
		const result = assembleMarkdown(ctx);
		expect(result).toContain("# Agent Skills");
		expect(result).toContain("Generated by skillet");
		expect(result).toContain("## sample");
		expect(result).toContain("---");
		expect(result.endsWith("\n")).toBe(true);
	});
});

describe("emitters (filesystem)", () => {
	let tmpDir: string;

	beforeEach(async () => {
		tmpDir = await mkdtemp(path.join(tmpdir(), "skillet-test-"));
	});

	afterEach(async () => {
		await rm(tmpDir, { recursive: true, force: true });
	});

	const makeCtx = (): EmitContext => ({
		projectDir: tmpDir,
		skills: [SAMPLE_SKILL],
		strategy: "eager",
	});

	it("CursorEmitter writes .mdc files", async () => {
		const emitter = new CursorEmitter();
		const result = await emitter.emit(makeCtx());

		expect(result.target).toBe("cursor");
		expect(result.files).toHaveLength(1);

		const content = await readFile(result.files[0], "utf-8");
		expect(content).toContain("---");
		expect(content).toContain("description: A sample skill for testing");
		expect(content).toContain("alwaysApply: true");
		expect(content).toContain("Do the thing.");

		const rulesDir = path.join(tmpDir, ".cursor", "rules");
		const entries = await readdir(rulesDir);
		expect(entries).toContain("sample.mdc");
	});

	it("CursorLegacyEmitter writes .cursorrules", async () => {
		const emitter = new CursorLegacyEmitter();
		const result = await emitter.emit(makeCtx());

		expect(result.files).toHaveLength(1);
		expect(result.files[0]).toContain(".cursorrules");

		const content = await readFile(result.files[0], "utf-8");
		expect(content).toContain("# Agent Skills");
	});

	it("ClaudeCodeEmitter writes CLAUDE.md", async () => {
		const emitter = new ClaudeCodeEmitter();
		const result = await emitter.emit(makeCtx());

		expect(result.files[0]).toContain("CLAUDE.md");
		const content = await readFile(result.files[0], "utf-8");
		expect(content).toContain("# Agent Skills");
	});

	it("CodexEmitter writes SKILL.md per skill", async () => {
		const emitter = new CodexEmitter();
		const result = await emitter.emit(makeCtx());

		expect(result.files).toHaveLength(1);
		expect(result.files[0]).toContain(path.join(".agents", "skills", "sample", "SKILL.md"));

		const content = await readFile(result.files[0], "utf-8");
		expect(content).toContain("name: sample");
		expect(content).toContain("Do the thing.");
	});

	it("GenericEmitter writes agent-context.md", async () => {
		const emitter = new GenericEmitter();
		const result = await emitter.emit(makeCtx());

		expect(result.files[0]).toContain("agent-context.md");
	});
});
