import type { InjectionStrategy, TargetRuntime } from "../schemas/manifest.js";
import type { SkillFrontmatter } from "../schemas/skill.js";

export interface SkillContent {
	id: string;
	frontmatter: SkillFrontmatter;
	body: string;
	inject?: "eager" | "lazy";
}

export interface EmitContext {
	projectDir: string;
	skills: SkillContent[];
	strategy: InjectionStrategy;
}

export interface EmitResult {
	target: TargetRuntime;
	files: string[];
}

export interface Emitter {
	target: TargetRuntime;
	emit(ctx: EmitContext): Promise<EmitResult>;
}

export function renderEager(skill: SkillContent): string {
	const header = `## ${skill.frontmatter.name}\n\n> ${skill.frontmatter.description}\n`;
	return `${header}\n${skill.body}`;
}

export function renderLazy(skill: SkillContent): string {
	return [
		`## ${skill.frontmatter.name}`,
		"",
		`> ${skill.frontmatter.description}`,
		"",
		`_This skill is loaded on demand. Trigger: mention "${skill.frontmatter.name}" or related tasks._`,
	].join("\n");
}

export function renderSkill(skill: SkillContent, defaultStrategy: InjectionStrategy): string {
	const effectiveStrategy = skill.inject ?? defaultStrategy;
	if (effectiveStrategy === "lazy") return renderLazy(skill);
	return renderEager(skill);
}

export function assembleMarkdown(ctx: EmitContext): string {
	const parts = ["# Agent Skills", "", "_Generated by skillet. Do not edit manually._", ""];

	for (const skill of ctx.skills) {
		parts.push(renderSkill(skill, ctx.strategy));
		parts.push("");
		parts.push("---");
		parts.push("");
	}

	return `${parts.join("\n").trimEnd()}\n`;
}
